/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'


export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/island.glb')

  return (
    <group ref={group} {...props} dispose={null} >
      <mesh
        geometry={nodes.Icosphere002.geometry}
        material={materials['Material.019']}
        position={[1.4, 8.15, -5.78]}
        scale={0.67}
        receiveShadow
      />
      <group position={[5.16, 3.16, 4.21]} rotation={[-0.95, 1.18, 1.03]} scale={[0.14, 0.14, 0.14]}>
        <mesh geometry={nodes.Plane012.geometry} material={nodes.Plane012.material} />
        <mesh geometry={nodes.Plane012_1.geometry} material={nodes.Plane012_1.material} />
      </group>
      <group position={[-2.26, 2.44, -6.91]} rotation={[-3.02, 1.34, -2.94]} scale={[0.14, 0.14, 0.14]}>
        <mesh geometry={nodes.Plane013.geometry} material={nodes.Plane013.material} />
        <mesh geometry={nodes.Plane013_1.geometry} material={nodes.Plane013_1.material} />
      </group>
      <group position={[-1.58, 2.46, -7.24]} rotation={[-0.24, 1.03, 0.23]} scale={[0.19, 0.19, 0.19]}>
        <mesh geometry={nodes.Plane014.geometry} material={nodes.Plane014.material} />
        <mesh geometry={nodes.Plane014_1.geometry} material={nodes.Plane014_1.material} />
      </group>
      <group position={[-0.25, 3, -1.87]} rotation={[-0.8, 1.32, 0.91]} scale={[0.16, 0.16, 0.16]}>
        <mesh geometry={nodes.Plane015.geometry} material={nodes.Plane015.material} />
        <mesh geometry={nodes.Plane015_1.geometry} material={nodes.Plane015_1.material} />
      </group>
      <group position={[3, 2.78, -0.26]} rotation={[0.24, -0.73, -0.05]} scale={[0.32, 0.32, 0.32]}>
        <mesh geometry={nodes.Cube002_1.geometry} material={nodes.Cube002_1.material} />
        <mesh geometry={nodes.Cube002_2.geometry} material={nodes.Cube002_2.material} />
        <mesh geometry={nodes.Cube002_3.geometry} material={nodes.Cube002_3.material} />
        <mesh geometry={nodes.Cube002_4.geometry} material={nodes.Cube002_4.material} />
      </group>
      <group position={[5.33, 3.76, -8]} rotation={[-3.02, -0.44, -3.13]} scale={[0.13, 0.13, 0.13]}>
        <mesh geometry={nodes.Plane016.geometry} material={nodes.Plane016.material} />
        <mesh geometry={nodes.Plane016_1.geometry} material={nodes.Plane016_1.material} />
      </group>
      <group position={[5.89, 4.01, -7.68]} rotation={[3.11, 0.16, 2.93]} scale={[0.13, 0.13, 0.13]}>
        <mesh geometry={nodes.Plane017.geometry} material={nodes.Plane017.material} />
        <mesh geometry={nodes.Plane017_1.geometry} material={nodes.Plane017_1.material} />
      </group>
      <group position={[5.39, 3.91, -8.65]} rotation={[-3.12, 0.94, 3.1]} scale={[0.17, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane018.geometry} material={nodes.Plane018.material} />
        <mesh geometry={nodes.Plane018_1.geometry} material={nodes.Plane018_1.material} />
      </group>
      <group position={[8.7, 4.35, 0.83]} rotation={[-3.12, 0.07, 2.94]} scale={[0.13, 0.13, 0.13]}>
        <mesh geometry={nodes.Plane019.geometry} material={nodes.Plane019.material} />
        <mesh geometry={nodes.Plane019_1.geometry} material={nodes.Plane019_1.material} />
      </group>
      <group position={[8.8, 4.75, 0.26]} rotation={[-3.09, -0.17, 2.96]} scale={[0.17, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane020.geometry} material={nodes.Plane020.material} />
        <mesh geometry={nodes.Plane020_1.geometry} material={nodes.Plane020_1.material} />
      </group>
      <group position={[-4.05, 2.23, -0.78]} rotation={[3.13, 0.06, 3.02]} scale={[0.42, 0.42, 0.42]}>
        <mesh geometry={nodes.Cube003.geometry} material={nodes.Cube003.material} />
        <mesh geometry={nodes.Cube003_1.geometry} material={nodes.Cube003_1.material} />
        <mesh geometry={nodes.Cube003_2.geometry} material={nodes.Cube003_2.material} />
        <mesh geometry={nodes.Cube003_3.geometry} material={nodes.Cube003_3.material} />
      </group>
      <group position={[5.39, 3.39, 5.35]} rotation={[-0.25, 0.78, 0.27]} scale={[0.17, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane021.geometry} material={nodes.Plane021.material} />
        <mesh geometry={nodes.Plane021_1.geometry} material={nodes.Plane021_1.material} />
      </group>
      <group position={[6.16, 3.42, 4]} rotation={[2.94, 0.22, 3.03]} scale={[0.17, 0.17, 0.17]}>
        <mesh geometry={nodes.Plane022.geometry} material={nodes.Plane022.material} />
        <mesh geometry={nodes.Plane022_1.geometry} material={nodes.Plane022_1.material} />
      </group>
      <group position={[-0.28, 2.52, 4.23]} rotation={[2.97, -0.22, 2.83]} scale={[0.43, 0.43, 0.43]}>
        <mesh geometry={nodes.Cube005.geometry} material={nodes.Cube005.material} />
        <mesh geometry={nodes.Cube005_1.geometry} material={nodes.Cube005_1.material} />
        <mesh geometry={nodes.Cube005_2.geometry} material={nodes.Cube005_2.material} />
        <mesh geometry={nodes.Cube005_3.geometry} material={nodes.Cube005_3.material} />
      </group>
      <mesh
        geometry={nodes.Plane.geometry}
        material={materials['Material.026']}
        position={[3.51, 1.7, -2.01]}
        rotation={[3.09, -1.05, 3.09]}
        scale={[12.57, 12.57, 12.57]}
      />
      <mesh
        geometry={nodes.Icosphere.geometry}
        material={materials['Material.027']}
        position={[3.79, 0.31, -1.87]}
        rotation={[3.09, -1.05, 3.09]}
        scale={[10, 10, 10]}
      />
    </group>
  )
}

useGLTF.preload('/island.glb')
